---
sudo: false
language: node_js
matrix:
    fast_finish: true
node_js:
    - 0.10
    - 4
    - 5
env:
    global:
        - CXX=g++-4.8
        - COZY_DESKTOP_DIR=tmp
services:
    - couchdb
cache:
    directories:
        - node_modules
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - gcc-4.8
            - g++-4.8

# install cozy stack for integration test
before_install:
    - cd
    - export INDEXES_PATH=/home/travis/build/indexes
    - mkdir -p $INDEXES_PATH
    - TESTED_NODE=$(node -v)
    - nvm install 4
    - nvm use 4
    - travis_retry npm -g install npm@latest-2
    - npm install forever coffee-script -g
    - git clone git://github.com/cozy/cozy-data-system.git
    - cd cozy-data-system
    - npm install #data-system
    - cp /home/travis/build/poupotte/cozy-desktop/token.js build/server/lib/token.js
    - cp /home/travis/build/poupotte/cozy-desktop/filters.js build/server/controllers/filters.js
    - pwd
    - NAME=data-system TOKEN=token forever start -o forever-ds.log -e forever-ds-err.log build/server.js
    - sleep 5
    - pwd
    - cd
    - git clone git://github.com/cozy/cozy-proxy.git
    - cd cozy-proxy
    - npm install
    - cp /home/travis/build/poupotte/cozy-desktop/device.js build/server/models/device.js
    - pwd
    - NAME=proxy TOKEN=token forever start -o forever-proxy.log -e forever-proxy-err.log build/server.js
    - sleep 5
    - 'curl -X POST -H "Content-Type: application/json" -d "{ \"email\": \"cozytest@cozycloud.cc\", \"password\": \"cozytest\", \"timezone\":\"Europe/Paris\"}" http://127.0.0.1:9104/register'
    - cd
    - git clone git://github.com/cozy/cozy-files.git
    - cd cozy-files
    - npm install
    - pwd
    - cd ~/cozy-data-system
    - coffee commands.coffee test-install files ../cozy-files/package.json
    - pwd
    - cd ~/cozy-files
    - NAME=files TOKEN=apptoken forever start -o forever-files.log -e forever-files-err.log build/server.js
    - sleep 3
    - nvm use $TESTED_NODE
    - cd /home/travis/build/poupotte/cozy-desktop
    - pwd

script:
    - npm run build
    - npm run lint
    - npm run test

after_failure:
    - pwd
    - ps aux | grep server.js
    - netstat -lntp
    - cat ~/cozy-data-system/forever-ds.log
    - cat ~/cozy-data-system/forever-ds-err.log
    - cat ~/cozy-proxy/forever-proxy.log
    - cat ~/cozy-proxy/forever-proxy-err.log
    - cat ~/cozy-files/forever-files.log
    - cat ~/cozy-files/forever-files-err.log
    - curl -v http://localhost:9101/
    - curl -v http://localhost:9104/
    - curl -v http://localhost:9121/
    - cat tmp/one.log
    - cat tmp/two.log
    - cat tmp/operations.log
